/**
 * Smart Translator - Message-Typen und Konstanten
 * Alle Nachrichten-Typen als UPPERCASE_SNAKE
 */

const MSG = {
  // Übersetzung
  TRANSLATE: 'TRANSLATE',
  TRANSLATE_BATCH: 'TRANSLATE_BATCH',
  TRANSLATE_PAGE: 'TRANSLATE_PAGE',
  TRANSLATE_WORD_AT_CURSOR: 'TRANSLATE_WORD_AT_CURSOR',
  TRANSLATION_STATUS: 'TRANSLATION_STATUS',

  // Seitenstatus
  PAGE_STATUS_CHANGED: 'PAGE_STATUS_CHANGED',
  GET_PAGE_INFO: 'GET_PAGE_INFO',
  GET_SELECTION: 'GET_SELECTION',
  RESTORE_PAGE: 'RESTORE_PAGE',
  LOAD_CACHED_TRANSLATION: 'LOAD_CACHED_TRANSLATION',

  // Ergebnisse zum Content-Script
  SHOW_TRANSLATION: 'SHOW_TRANSLATION',
  SHOW_ERROR: 'SHOW_ERROR',

  // Verlauf
  GET_HISTORY: 'GET_HISTORY',
  ADD_TO_HISTORY: 'ADD_TO_HISTORY',
  CLEAR_HISTORY: 'CLEAR_HISTORY',

  // Einstellungen
  GET_SETTINGS: 'GET_SETTINGS',
  GET_API_TYPE: 'GET_API_TYPE',
  UPDATE_EBOOK_DOMAINS: 'UPDATE_EBOOK_DOMAINS',

  // Token-Statistiken
  GET_TOKEN_STATS: 'GET_TOKEN_STATS',
  UPDATE_TOKEN_STATS: 'UPDATE_TOKEN_STATS',
  RESET_TOKEN_STATS: 'RESET_TOKEN_STATS',

  // Cache (Content-Script)
  GET_CACHE_INFO: 'GET_CACHE_INFO',
  CLEAR_CACHE: 'CLEAR_CACHE',

  // Cache-Server
  CACHE_SERVER_BULK_GET: 'CACHE_SERVER_BULK_GET',
  CACHE_SERVER_BULK_STORE: 'CACHE_SERVER_BULK_STORE',
  CACHE_SERVER_BULK_DELETE: 'CACHE_SERVER_BULK_DELETE',
  CACHE_SERVER_DELETE_BY_URL: 'CACHE_SERVER_DELETE_BY_URL',
  CACHE_SERVER_GET_URL_STATS: 'CACHE_SERVER_GET_URL_STATS',
  CACHE_SERVER_GET_ALL_BY_URL: 'CACHE_SERVER_GET_ALL_BY_URL',
  CACHE_SERVER_DELETE_BY_HASH: 'CACHE_SERVER_DELETE_BY_HASH',
  CACHE_SERVER_DELETE_BY_DOMAIN: 'CACHE_SERVER_DELETE_BY_DOMAIN',
  CACHE_SERVER_LIST_URLS: 'CACHE_SERVER_LIST_URLS',
  CACHE_SERVER_CLEAR_ALL: 'CACHE_SERVER_CLEAR_ALL',
  GET_CACHE_SERVER_STATS: 'GET_CACHE_SERVER_STATS',

  // Export
  EXPORT_MARKDOWN: 'EXPORT_MARKDOWN',
  EXPORT_TEXT: 'EXPORT_TEXT',

  // UI / Navigation
  OPEN_SIDE_PANEL: 'OPEN_SIDE_PANEL',
  SIDEPANEL_TRANSLATE: 'SIDEPANEL_TRANSLATE',
  SIDEPANEL_SHOW_CACHE: 'SIDEPANEL_SHOW_CACHE'
};
